language: c
os:
  - linux

compiler:
  - gcc

before_script:
  - sudo apt-get update
  - sudo apt-get install -y libstdc++6-4.6-dev libc6-dev-i386 libx32ncurses5-dev libncurses5-dev
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y gcc-multilib g++-multilib
script:
  bash bootstrap.sh

